script: bash ./deploy.sh
language: php
php:
- 7.2
env:
  global:
  - GH_REF: github.com/UDOOboard/Gear-Docs.git
  - secure: "w8jiqtkvIsi+cs0CwIaU/55oz/o42c4x3TVmHZMMBmaojgNv1n7mQW0uTF3rLvRT7S6DqcxlBDomI9Xh4FQ0NpGB+t6ROhsfuwuLgbuPRdkyJ3+zo0joJtlsnvBMUqXsN4bZMpTvwLIN19+78e4yX8U66sAlG5vXrgYdgAWcXwBKe8dPHeuFUP2Ji8DkaU9eaJf5nTDJFg344UI/rrqRZL/2csRzJ0Hl7lfpQHpWAsBx6DHhlUm2slyFjuV8pU+hU5bPS0Y9vvVJ65l5hXQKeZQoD4/Ta/DJWw6uT3JPuXTEqULynYvCrg6e6Awm54ORKX58Cdb6+nQ6BAqDTnf45kMRnaCvm64cETZ4t3nSSld84ZKTqVjNUo7FO9o5tdhfxT0Qf2s0skzUkrkeS2BHTKaON/uNBk5lJ2wVgnbkfAaoOP5WxWyhr2gdXuzekNOlB3n88sKbJnWMvfTTtDLIb2liTES+rbQhypf6hCdw6oqSbeAsWjZNxkRyxmU1iTwtRO9LmF/yrXdRNS7OlVxP/RgjofEKufVTN4D4u6vTzmK/HYvXTX/lPMZU8AYBDDQKmRkr8tEgPg+bRSDjqJFaMSnPqvvFCifm4pN5QDSzVvMMIZrzYyKzaBCLNYIETKsV3V7GmL8d0PSg/DBZyMSfUPUpM3HrYDoqA4wGLLGV8WA="
